import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // This tells Docusaurus: "Look at the docs folder and build the sidebar for me"
  knowledgeBaseSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means generate from the root of the docs folder
    },
  ],
};

export default sidebars;